---

  # ansible-playbook -i hosts sonic-playbook.yaml -e "ansible_user=admin ansible_ssh_pass=admin ansible_sudo_pass=admin" -vv
  # ansible-playbook -i hosts sonic-playbook.yaml -e "ansible_user=cisco ansible_ssh_pass=cisco123 ansible_sudo_pass=cisco123" -vv


- name: Apply config_db.json and frr.conf to SONiC routers
  hosts: sonic
  become: true
  tasks:

    - name: Copy config_baseline.json files
      copy:
        src: "../sonic-config/{{ inventory_hostname }}/config_db.json"
        dest: "/etc/sonic/config_db.json"
        mode: 0644

    - name: sonic config load
      command: "sudo config load /etc/sonic/config_db.json -y"
      ignore_errors: yes

    - name: restart hostname service
      command: sudo systemctl restart hostname-config
      ignore_errors: yes

    - name: Copy loopback shell script
      copy:
        src: "../sonic-config/{{ inventory_hostname }}/loopback.sh"
        dest: "/etc/sonic/loopback.sh"
        mode: 0755

    - name: run loopback shell script
      command: "/etc/sonic/loopback.sh"
      ignore_errors: yes

    - name: Save sonic configuration
      command: "sudo config save -y"
      ignore_errors: yes

    - name: add sr0 loopback interface
      command: "sudo ip link add sr0 type dummy"
      ignore_errors: yes

    - name: activate sr0 loopback interface
      command: "sudo ip link set sr0 up"
      ignore_errors: yes

    - name: vrf sysctl
      command: "sudo sysctl -w net.vrf.strict_mode=1"
      ignore_errors: yes

    - name: Delete default sonic-vs BGP config
      ansible.builtin.command: >
        vtysh -c "configure terminal"
        -c "no router bgp 65100"
        -c "exit"
      ignore_errors: yes

- name: Load frr config
  hosts: sonic
  become: true
  tasks:

    - name: Create a backup of the existing frr config file
      command: mv /etc/sonic/frr/bgpd.conf /etc/sonic/frr/bgpd.conf.bak
      args:
        creates: /etc/sonic/frr/bgpd.conf.bak
      ignore_errors: yes
      register: backup_result

    - name: Copy frr config files
      copy:
        src: "../sonic-config/{{ inventory_hostname }}/frr.conf"
        dest: "/etc/sonic/frr/bgpd.conf"
        mode: 0644

    - name: Load the FRR config through vtysh
      command: vtysh -f /etc/sonic/frr/bgpd.conf
      ignore_errors: yes
      register: frr_load_result

    - name: sonic config load just to make sure
      command: "sudo config load -y"
      ignore_errors: yes

- name: validate SONiC local srv6 SIDs
  hosts: sonic
  become: true
  tasks:

    - name: check srv6 SIDs
      shell: "ip -6 route show | grep -e seg6 -e fe00"
      register: srv6_sid_result

    - name: print srv6 SIDs
      debug:
        var: srv6_sid_result.stdout

#- name: Customize MOTD on specific SONiC node
#  hosts: spine00
#  become: true
#  tasks:
#    - name: Set custom MOTD
#      copy:
#        content: |
#          â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—â–ˆâ–ˆâ•—â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•— â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•— â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—               â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•— â–ˆâ–ˆâ•—   â–ˆâ–ˆâ•— â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—               â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•— â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•— â–ˆâ–ˆâ–ˆâ•—   â–ˆâ–ˆâ•—â–ˆâ–ˆâ•— â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—
#          â–ˆâ–ˆâ•”â•â•â•â•â•â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•”â•â•â•â•â•â–ˆâ–ˆâ•”â•â•â•â•â•â–ˆâ–ˆâ•”â•â•â•â–ˆâ–ˆâ•—              â–ˆâ–ˆâ•”â•â•â•â•â•â–ˆâ–ˆâ•”â•â•â–ˆâ–ˆâ•—â–ˆâ–ˆâ•‘   â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•”â•â•â•â•â•               â–ˆâ–ˆâ•”â•â•â•â•â•â–ˆâ–ˆâ•”â•â•â•â–ˆâ–ˆâ•—â–ˆâ–ˆâ–ˆâ–ˆâ•—  â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•”â•â•â•â•â•
#          â–ˆâ–ˆâ•‘     â–ˆâ–ˆâ•‘â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—â–ˆâ–ˆâ•‘     â–ˆâ–ˆâ•‘   â–ˆâ–ˆâ•‘    â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—    â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•”â•â–ˆâ–ˆâ•‘   â–ˆâ–ˆâ•‘â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—     â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—    â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—â–ˆâ–ˆâ•‘   â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•”â–ˆâ–ˆâ•— â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘     
#          â–ˆâ–ˆâ•‘     â–ˆâ–ˆâ•‘â•šâ•â•â•â•â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘     â–ˆâ–ˆâ•‘   â–ˆâ–ˆâ•‘    â•šâ•â•â•â•â•    â•šâ•â•â•â•â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•”â•â•â–ˆâ–ˆâ•—â•šâ–ˆâ–ˆâ•— â–ˆâ–ˆâ•”â•â–ˆâ–ˆâ•”â•â•â•â–ˆâ–ˆâ•—    â•šâ•â•â•â•â•    â•šâ•â•â•â•â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘   â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘â•šâ–ˆâ–ˆâ•—â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘     
#          â•šâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—â–ˆâ–ˆâ•‘â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•‘â•šâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—â•šâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•”â•              â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘  â–ˆâ–ˆâ•‘ â•šâ–ˆâ–ˆâ–ˆâ–ˆâ•”â• â•šâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•”â•              â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•‘â•šâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•”â•â–ˆâ–ˆâ•‘ â•šâ–ˆâ–ˆâ–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘â•šâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—
#           â•šâ•â•â•â•â•â•â•šâ•â•â•šâ•â•â•â•â•â•â• â•šâ•â•â•â•â•â• â•šâ•â•â•â•â•â•               â•šâ•â•â•â•â•â•â•â•šâ•â•  â•šâ•â•  â•šâ•â•â•â•   â•šâ•â•â•â•â•â•               â•šâ•â•â•â•â•â•â• â•šâ•â•â•â•â•â• â•šâ•â•  â•šâ•â•â•â•â•šâ•â• â•šâ•â•â•â•â•â•
#
#          Welcome to the SRv6 Lab! ğŸš€
#          Give/show this SID to Nicolas: fc00:congrats:on:th3:csco:b00k | Node ID: spine00 | "Hope you have fun !"
#        dest: /etc/motd
#        mode: '0644'