hubble:
  enabled: false
  relay:
    enabled: false
ipv6:
  enabled: true
nodeinit:
  enabled: true
debug:
  enabled: true
enterprise:
  featureGate:
    approved:
    - SRv6
    - EnterpriseBGPControlPlane
  srv6:
    enabled: true
    encapMode: reduced
    locatorPoolEnabled: true
  bgpControlPlane:
    enabled: true
k8s:
  requireIPv4PodCIDR: true
  requireIPv6PodCIDR: true
ipam:
  mode: kubernetes
cni:
  exclusive: false
ipv4NativeRoutingCIDR: 10.0.0.0/8
ipv6NativeRoutingCIDR: c::/32