# berlin netplan

network:
  ethernets:
    ens3:
      addresses:
      - 192.168.122.101/24 
      #gateway4: 192.168.122.1

    ens4:
      addresses:
      - 10.8.1.2/24
      - fc00:0:0800:1::2/64
      routes:
        - to: 0.0.0.0/0
          via: 10.8.1.3
          metric: 100
        - to: 10.0.0.0/8
          via: 10.8.1.1
        - to: fc00:0::/32
          via: fc00:0:0800:1::1
      nameservers:
        addresses:
        - 8.8.8.8
        search:
        - demo.dcloud.cisco.com
    # ens5:
    #   addresses:
    #   - fcbb:0:0800:1::/64
    #   routes:
    #     - to: fcbb:0::/32
    #       via: fcbb:0:0800:1::1
  version: 2